---
title: ''
output: html_document
---

```{r setup, include=FALSE}

## Loading Packages
library(forcats)
library(DT)
library(readxl)
library(tidyverse)
library(highcharter)
library(glue)
library(acs)
library(stringr)

## Setting Formatting for output
knitr::knit_hooks$set(inline = function(x) { if(!is.numeric(x)){ x }else{ prettyNum(round(x,2), big.mark=",", digits=6) } })
## Formatting for Graphics
hcoptslang <- getOption("highcharter.lang")
hcoptslang$thousandsSep <- ","
options(highcharter.lang = hcoptslang)


#Read in files

msa_pop<- readxl::read_xlsx("raw_data/metro/msa_aapi_prop.xlsx")

## Using the lookup table to merge in Group Names and the proper population ID names
pop_id_lookup <- read_csv("raw_data/pop_id_lookup.csv") #Look-up table



msa_pop <- msa_pop %>% rename(
  MSA = geodisplaylabel,
  `Total Population`= est_tot_pop,
  `Asian Alone` = est_aa_alone,
  `Asian Alone % Total Pop` = pct_aa_alone,
  `Asian Combo` = est_aa_combo,
  `Asian Combo % Total Pop` = pct_aa_combo,
  `NHPI Alone` = est_nhpi_alone,
  `NHPI Alone % Total Pop` = pct_nhpi_alone,
  `NHPI Combo` = est_nhpi_combo,
  `NHPI Combo % Total pop` = pct_nhpi_combo
)

msa_rawnumbers <- c("MSA", "Total Population", "Asian Alone", "Asian Combo", "NHPI Alone", "NHPI Combo")
msa_percent <- c("MSA", "Total Population", "Asian Alone % Total Pop", "Asian Combo % Total Pop", "NHPI Alone % Total Pop", "NHPI Combo % Total pop")


 msa_display_table <- function(data, which_estimates){
   data %>%
     select(which_estimates)%>%
     arrange(MSA)%>%
    select(MSA,starts_with("Total population"),everything()) %>%
      datatable(extensions = 
                list("Buttons" = NULL, 'FixedColumns'= T, "Scroller"=T),
              rownames= FALSE, 
              options = list(
                dom = 'rtB',
                buttons = c('copy', 'csv', 'excel'),
                scrollX = TRUE,
                fixedColumns = list(leftColumns = 1),
                lengthMenu = c(25, 50, 100), pageLength = 50))
 }


```



```{r setup pop, include = FALSE}


###Data highlight sentence
msa_largestAAprop <- msa_pop %>% top_n(1, `Asian Alone % Total Pop`) %>% pull(MSA)
msa_largestAAprop_number <- msa_pop %>% top_n(1, `Asian Alone % Total Pop`) %>% pull(`Asian Alone % Total Pop`)
msa_largestAAprop_number<- round(msa_largestAAprop_number*100,0)


```



<div class="jumbotron">
  <div class="container">
  <h1>Metro Area Data</h1>
  <p> About `r msa_largestAAprop_number`% of the population in `r msa_largestAAprop` is Asian American, the highest in the country.</p>
<div class="btn-group" role="group" aria-label="Basic example">
  <a href="metro_data.html#percent-aapi-population" type="button" class="btn btn-primary">AAPI Population</a>
  <a href="metro_data.html#education" type="button" class="btn btn-primary">Education</a>
  <a href="metro_data.html#limited-english-proficiency" type="button" class="btn btn-primary">LEP</a>
</div>
</div>
</div>

# Population {.tabset .tabset-fade .tabset-pills}
<a href="#top"><button class="btn btn-outline-primary center-block btn-small"> Back to Top</button></a>

> Attribution sentence here


## Percent AAPI Population 


```{r pop-pct, echo=FALSE, message=FALSE, warning=FALSE}

  
 msa_display_table(msa_pop,msa_percent) %>% 
  formatCurrency(columns = c(2),currency = "", interval = 3, mark = ",", digits=0) %>%
  formatPercentage(columns = c(3,4,5,6),digits = 2)


```


## AAPI Population


```{r pop-number, echo=FALSE, message=FALSE, warning=FALSE}

  
msa_display_table(msa_pop,msa_rawnumbers) %>% 
  formatCurrency(columns = c(2,3,4,5,6),currency = "", interval = 3, mark = ",", digits=0)


```

